name: Lint Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/bun-action@v1.7.3

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint
